baseURL = 'https://piggybotanist.github.io/'
languageCode = 'en-us'
title = 'Portfolio'
theme = 'relearn'

[languages]
  [languages.en]
    title = 'About My Website'
    weight = 1
    languageCode = 'en'
    languageName = 'English'
    [languages.en.params]
      landingPageName = '<i class="fa-fw fas fa-home"></i> Home'

  [[languages.en.menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-github"></i> '
    name = 'GitHub'
    url = 'https://github.com/PiggyBotanist/'
    weight = 10

  [[languages.en.menu.shortcuts]]
    pre = '<i class="fa-fw fab fa-linkedin"></i> '
    name = 'LinkedIn'
    url = 'https://www.linkedin.com/in/jeremy-kh-chang/'
    weight = 20

[markup]
[markup.goldmark.renderer]
  unsafe = true

[params]
  additionalContentLanguage = ['en']
  themeVariantAuto = ['relearn-light', 'relearn-dark']
  alwaysopen = ''
  breadcrumbSeparator = '>'
  collapsibleMenu = true
  customMathJaxURL = ''
  customMermaidURL = ''
  customOpenapiURL = ''
  disableAnchorCopy = false
  disableAnchorScrolling = false
  disableAssetsBusting = false
  disableBreadcrumb = false
  disableDefaultRelref = false
  disableExplicitIndexURLs = false
  disableGeneratorVersion = false
  disableHoverBlockCopyToClipBoard = false
  disableInlineCopyToClipBoard = true
  disableLandingPageButton = true
  disableLanguageSwitchingButton = false
  disableNextPrev = false
  disableRandomIds = false
  disableRootBreadcrumb = true
  disableSearch = false
  disableSearchHiddenPages = false
  disableSearchIndex = false
  disableSearchPage = false
  disableSeoHiddenPages = true
  disableShortcutsTitle = false
  disableTagHiddenPages = false
  disableTermBreadcrumbs = false
  disableToc = false
  editURL = 'https://github.com/McShelby/hugo-theme-relearn/edit/main/exampleSite/content/${FilePath}'
  externalLinkTarget = '_self'
  highlightWrap = true
  images = ['images/hero.png']
  linkTitle = 'Piggybotanist'
  math = false
  mathJaxInitialize = '{}'
  mermaidInitialize = '{ "securityLevel": "loose" }'
  mermaidZoom = true
  minify = ''
  ordersectionsby = 'weight'
  searchIndexURL = 'searchindex.js'
  searchPageURL = 'search'
  showVisitedLinks = true
  titleSeparator = '::'

  [params.author]
    name = 'Sören Weber'

  [[params.boxStyle]]
    color = 'gold'
    i18n = ''
    icon = 'rainbow'
    identifier = 'magic'
    title = 'Magic'

  [params.image]
    errorlevel = 'error'

  [params.imageEffects]
    border = true
    lazy = true
    lightbox = true
    shadow = false

  [params.include]
    errorlevel = 'error'

  [params.link]
    errorlevel = 'error'

  [params.mermaid]
    force = false

  [params.openapi]
    errorlevel = 'error'

  [params.oppenapi]
    force = false

  [[params.sidebarmenus]]
    disableTitle = true
    identifier = 'home'
    main = true
    pageRef = ''
    type = 'page'

  [[params.sidebarmenus]]
    disableTitle = false
    identifier = 'shortcuts'
    main = false
    type = 'menu'

  [params.social]
    facebook_admin = ''
    twitter = ''

  [[params.themeVariant]]
    auto = []
    identifier = 'relearn-auto'
    name = 'Default Theme'

  [[params.themeVariant]]
    identifier = 'zen-light'

  [[params.themeVariant]]
    identifier = 'zen-dark'

  [[params.themeVariant]]
    identifier = 'relearn-light'
    name = 'Custom Light'

  [[params.themeVariant]]
    identifier = 'relearn-dark'
    name = 'Custom Dark'

  [[params.themeVariant]]
    identifier = 'relearn-bright'
    name = 'Custom Bright'

  [[params.themeVariant]]
    identifier = 'neon'

  [[params.themeVariant]]
    identifier = 'purple'

  [[params.themeVariant]]
    identifier = 'blue'

  [[params.themeVariant]]
    identifier = 'green'

  [[params.themeVariant]]
    identifier = 'red'